version: "3.9"
services:
  web:
  baggins.api.rest:
    image: my.image.name:rc2
    build: .
      context: ../..
      dockerfile: ./Dockerfile
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"

